#### register check
POST http://localhost:9000/auth/register
Content-Type: application/json

{
    "userName":"sahooranjit519@gmail.com", 
    "password":"sahooranjit519@gmail.com",
    "name":"ranjit",
    "address":"Bhubaneswer",
     "phoneNumber":"9937480480"
}
#### login check
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "userName":"sahooranjit519@gmail.com", 
    "password":"sahooranjit519@gmail.com"
  
}